image: node:latest

stages:
  - build
  - package

build:
  stage: build
  artifacts:
    when: on_failure
  before_script:
    # installing dependencies
    - npm install
  script:
    - npm run build

package:
  stage: package
  before_script:
    # installing dependencies and zip
    - npm install
    - if [[ ! `builtin type -p zip` ]]; then apt update &>/dev/null && apt install zip -yy &>/dev/null; fi
  script:
    - npm run zip
    - rm -rf target
    - mv _build asusctl-gex@asus-linux.org
  artifacts:
    name: "asusctl-gex-$CI_COMMIT_TAG"
    untracked: true
    expire_in: 2 days
  only:
    - tags
  except:
    - master