#!/bin/sh
UUID=`grep -E '^[ ]*"uuid":' metadata.json | sed 's@^[ ]*"uuid":[ ]*"\(.\+\)",[ ]*@\1@'`
INSTALLBASE=~/.local/share/gnome-shell/extensions

if [ -d "$INSTALLBASE/$UUID" ]
then
  rm -rf "$INSTALLBASE/$UUID/*"
else
  mkdir -p "$INSTALLBASE/$UUID"
fi

cp -r _build/* "$INSTALLBASE/$UUID/"
gnome-extensions enable "$UUID"