#!/bin/sh
UUID = $(shell grep -E '^[ ]*"uuid":' ../metadata.json | sed 's@^[ ]*"uuid":[ ]*"\(.\+\)",[ ]*@\1@')
INSTALLBASE = $(HOME)/.local/share/gnome-shell/extensions

gnome-extensions disable $(UUID)
rm -rf $(INSTALLBASE)/$(INSTALLNAME)